### PR TITLE
Update NEXTCLOUD.snap--backup_nextcloud-export.md

### PR DESCRIPTION
**Pull request by Poecilia**
Hi,
I am totally new to pull requests, so I hope I'm doing this correctly, but someone on the Nextcloud help forums really helped me out with the information I'm adding.

### CODE REVIEW

**Comment by scubamuc** [comment]
Hi @Poecilia, 

well I'm afraid I also have no idea how github works... your request is really great great though. I didn't think anyone would read my wiki.

I'd prefer a different base though. If you create a new *.md file, say `NEXTCLOUD.snap--backup_external-media_nextcloud-export.md` then I'd try adding a new "external" topic to the wiki. would you allow me to make minimal changes to you grammar?

Thanks, great work

**Comment by Poecilia** [comment]
Yes, feel free to make changes. I'll take a look at the new .md file tomorrow.

Have you read the wiki on the main nextcloud snap page?

**Comment by scubamuc** [comment]
Hi @Poecilia , no worries, take your time. I'll try merging your request, just to see how it works :-)
No I haven't seen the nextcloud wiki. I've only seen the nesctloud-snap wiki. That's why I wanted to create my own wiki. I have plenty more documents, but they're all in german, so i'll need a while to translate them if at all.

**Comment by Poecilia** [comment]
I meant this one: https://github.com/nextcloud-snap/nextcloud-snap/wiki

**Comment by scubamuc** [comment]
Yes I've seen this wiki... I'm not sure why Kyle doesn't allow editing of his wiki... that's why I started my own nextcloud-snap wiki. 

I have to admit, that I'm an absolute newbie concerning github... I simply started my github without a real plan. Its great that you found my wiki. How did you find it? Until now you're the only user who's reacted to my entries. I'm quite chuffed about that :-)

**Comment by Poecilia** [comment]
It's a good way for both of us to learn. I am not a coder, but am interested in using the format of github to create text (I am a teacher). I too, have lots of notes on my NC snap setup, also on a hardware PC. I found you by searching for nextcloud snap wiki. I thought maybe the original NC snap wiki may have had its own github page at some point, now archived, but I couldn't find that, and ended up on your page.

I have seen others use github for text creation (as opposed to coding). I just wonder what the best approach is there - using the .md files with pull requests or direct editing of the wiki. I suspect the latter can get confusing and messy. I am currently watching some tutorials about github to learn. It's all very interesting - thanks for your open attitude!

**Comment by scubamuc** [comment]
well I'm also keen to learn. 
Any suggestions are welcome. If you have any Ideas on how to "share" this repository, or if you prefer making a new repository and creating a joint venture, I'm game!
What subjects do you teach? 
I'm situated in Munich, where are you from?

**Comment by Poecilia** [comment]
I'm in Belgium and teach English literature and language. I'm happy to just learn by contributing here for now. On reflection: I wonder if the 'wiki' on your github page is meant as the wiki for your project, which is to create a kind of wiki manual, if that makes sense. I think I've seen github projects for the creation of a guide or wiki in the past.

**Comment by scubamuc** [comment]
Hi @Poecilia, 

yip that was more or less my idea. I like scripting and do a lot of scripting. So I keep my scripts in my repo... mostly concerning my own set-up. I like to automate things with scripts. that way I have less work in my free time. I made it public just in case someone finds it useful. Its no good keeping things to yourself if it can help others. 

So what would you suggest? Would you prefer a different new combined project or try to adapt mine. I'd be glad to help with a combined project? I'd be "forced" to start translating my notes :-)

My mother-tongue is kind of similar to Belgian, I speak Afrikaans. Its closer to Dutch, but similar. "miskien kan jy my ook verstaan as ek my moedertaal gesels?". But I've been in Germany so long that I tend to forget the vocabulary. Even my English vocabulary suffers without practice.

**Comment by Poecilia** [comment]
Yes, I can understand it :) I think it's best to just keep your current project.

**Comment by Poecilia** [comment]
Hi @scubamuc ,

I've done some reading and video watching:

1. People definitely use github for text-based projects rather than code. Here is an example of a (now archived) guide project: https://github.com/monero-ecosystem/monero-GUI-guide. 
2. When working on text, there is no real reason to use the command terminal 'git' application locally; you can just work within the github website with markdown (except if you want to export the whole thing somewhere).
3. Text-based github projects I've seen seem to put all the articles or chapters into one folder. They also tend to create a hyper-linked table of contents in the readme.md file for quick access. We should maybe do that. We could even create an 'en' folder for English and a 'ger' folder for German.

It's at the moment not clear to me what the product of your github project is. If it is a wiki, where will it be published? Would you just copy & paste the latest .md files into the github project's own wiki? It might be better to export the articles somehow to an external wiki, pdf, epub book, or website, though I'm not sure how that works. The archived monero wallet gui guide explains how they use a tool called 'pandoc' for this, in which case you would have to pull the latest chapters from Github to your own computer using the git tool.

**Comment by scubamuc** [comment]
Hi @Poecilia, 

thanks for doing the research.

I*ve been thinking about this and have decided, that I'm going to keep my GitHub as it is and simply add personal interest stuff to it when I feel I need to share. Its a great space to store my scripts and share if needed. Other than that... I'm afraid it'll transform into "work" instead of "hobby" and I can't do with that at this time.

Your ideas are great and I'd sure assist where I can. Keep me posted if you decide to build a wiki on your GitHub. I'll assist where I can. 

As for your pull request, that was a great experience. I won't be merging that with my notes, because I don't store my data on removable media at all, so that doesn't apply to my setup.

**Comment by Poecilia** [comment]
Hi @scubamuc 

Yes, I totally understand what you mean about projects turning into work :). Perhaps at some future point we can work on a guide of some sort collaboratively. Thanks also for allowing me to experiment with the pull request etc. on your page. I learned a lot from it. I can't believe Linus Torvalds created both linux and git. 

Coincidentally, I came to a similar conclusion as well, to try and set up a personal notes & documents page here. I think it's possible to turn off the pull request option. I also want to look into that Github Pages function.

All the best!

**Comment by scubamuc** [comment]
Hi @Poecilia,

thank you so much for your input! You'll notice that I put some new effort into my GitHub due to your feedback.

Yes it is possible to deactivate the pull request option. I've gone ahead and deactivated it on my site already. You tip about using the Readme.md File instead of the GitHub wiki-structure was great advice too. I've deleted my GitHub wiki and rewritten the Readme file... what do you think? Is it better that way?

Did you know that Linus is an avid scuba diver too? I contacted him personally once. He even answered and was friendly.

Thank you for your great contact, its been fun talking and comparing notes.

**Comment by Poecilia** [comment]
I think it looks good. I suppose if you begin writing a lot, then you could put the text files into a folder and create a hyperlinked table of contents page in the readme file instead.

I'm playing around with the github pages feature. You have to create a new repository titled username.github.io and add an index.html file. Looks like this: https://poecilia.github.io/  It only works if your username is the repository name.

I can't figure out how to leave your project as contributor. Please feel free to kick me out :)

**Comment by scubamuc** [comment]
Hi @Poecilia, 

that's great, I added a repository as you suggested. I simply copied my Readme.md into the repository, renamed it to README.md and it worked fine! See here: https://scubamuc.github.io/

I'm trying to figure out how to remove you as a contributor... I think its stuck there because of your merge after the pull request.... but it doesn't bug me much :-)

**Comment by Poecilia** [comment]
I think in 'settings' - 'repositories' you should be able to remove me.

Cool that Pages worked!

**Pull request merged**
